---
- name: create database
  mysql_db: name={{ wp_db_name }} state=present

- name: create database user
  mysql_user: name={{ wp_db_user }} password={{ wp_db_pass }} priv=*.*:ALL state=present

- name: add php-fpm config
  template: src=php-fpm.conf.j2 dest=/etc/php5/fpm/pool.d/wordpress.conf
  sudo: true
  notify:
    - restart php-fpm

- name: add nginx config
  template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/site-{{ server_hostname }}.conf
  sudo: true

- name: enable nginx config
  file: src=/etc/nginx/sites-available/site-{{ server_hostname }}.conf dest=/etc/nginx/sites-enabled/site-{{ server_hostname }}.conf state=link
  sudo: true
  notify:
    - restart nginx

- name: download wp-cli
  get_url: url=https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar dest=/usr/local/bin/wp
  sudo: true

- name: make wp-cli executable
  file: path=/usr/local/bin/wp owner=vagrant mode="u+x"
  sudo: true

- name: test if destination exists
  shell: test -d {{ server_root }} && echo "exist" || echo ""
  register: is_folder_created

- name: download latest if not present
  command: wp core download --path={{ server_root }}
  when: is_folder_created.stdout != "exist"

- name: test if config exists
  shell: test -f {{ server_root }}/wp-config.php && echo "exist" || echo ""
  register: is_config_created

- name: configure
  command: wp core config --path={{ server_root }} --dbname={{ wp_db_name }} --dbuser={{ wp_db_user }} --dbpass={{ wp_db_pass }}
  when: is_config_created.stdout != "exist"

- name: test if installed
  shell: wp core is-installed --path={{ server_root }} && echo "installed" || echo ""
  register: is_installed

- name: install
  command: wp core install --path={{ server_root }} --admin_user={{ wp_admin_user }} --admin_password={{ wp_admin_pass }} --admin_email={{ wp_admin_email }} --url="http://{{ server_hostname }}/" --title="{{ wp_title }}"
  when: is_installed.stdout != "installed"
