---
- name: install
  apt: name={{ item }} state=present
  sudo: true
  with_items:
    - php5-cli
    - php5-common
    - php5-dev

- name: install extensions
  apt: name={{ item }} state=present
  sudo: true
  with_items:
    - php5-curl
    - php5-gd
    - php5-imap
    - php5-intl
    - php5-mcrypt
    - php5-ming
    - php5-mysql
    - php-pear
    - php5-ps
    - php5-pspell
    - php5-recode
    - php5-snmp
    - php-soap
    - php5-sqlite
    - php5-tidy
    - php5-xdebug
    - php5-xmlrpc
    - php5-xsl
